export * from './addHighlight'
export * from './getIsFavorite';
export * from './addToFavorite';
export * from './removeFromFavorite';
export * from './addNote';
export * from './getIndexOfTargetNews'
export * from './getIsTargetPartAlreadyHighlighted'
export * from './getArrayOfChunksOfTargetPart'
export * from './addNewHighlightToArrayOfHighlights'
export * from './updateFavoriteNewsWithNewHighlight'
export * from './updateFavoriteNewsWithNewNote'
export * from './getIsTargetPartAlreadyHasNotes'
